version: 2

sources:
  - name: raw
    database: METRICMIND
    schema: RAW
    tables:
      - name: orders
      - name: customers
      - name: order_items
      - name: payments
      - name: products
      - name: sellers
      - name: reviews
      - name: category